<TodoScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 15
        Label:
            text: "To-Do List"
            font_name: 'Roboto-Regular'
            font_size: '26sp'
            color: app.theme_colors[1]
            size_hint_y: 0.25
        Label:
            text: root.todo_list
            font_name: 'Roboto-Regular'
            font_size: '18sp'
            color: app.theme_colors[1]